name: Python package CI

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel

      - name: Build sdist
        run: |
          python setup.py sdist

      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      - name: Test
        run: |
          pip install pytest pytest-azurepipelines
          pip install .
          python -m pytest --pyargs prince_cr --junitxml=junit/test-results.xml

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
